---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8

suites:
  - name: 11-2-0-1-0
    run_list:
      - recipe[oracle-client-11-2-0-1-0]
    attributes:
      common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
  - name: 12-1-0-2-0
    run_list:
      - recipe[oracle-client-12-1-0-2-0]
    attributes:
      common_artifact_repo: <%= ENV['COMMON_ARTIFACT_REPO'] %>
